# Etapa 1: Build Angular
FROM node:20-alpine AS build
WORKDIR /src
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx ng build --configuration=production

# Etapa 2: Nginx sirve los estáticos
FROM nginx:alpine AS final
COPY --from=build /src/dist/sapienxa/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80