server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Crítico para Angular Router — sin esto los refrescos dan 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}